/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WhatIsPmRouteImport } from './routes/what-is-pm'
import { Route as WebinarsRouteImport } from './routes/webinars'
import { Route as TrainingPartnersRouteImport } from './routes/training-partners'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as TemplatesRouteImport } from './routes/templates'
import { Route as StoreHelpRouteImport } from './routes/store-help'
import { Route as StoreRouteImport } from './routes/store'
import { Route as SitemapRouteImport } from './routes/sitemap'
import { Route as ReportPdusRouteImport } from './routes/report-pdus'
import { Route as PurchasingTermsRouteImport } from './routes/purchasing-terms'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PressRouteImport } from './routes/press'
import { Route as PmiBlogRouteImport } from './routes/pmi-blog'
import { Route as PmbokGuideRouteImport } from './routes/pmbok-guide'
import { Route as OnlineCoursesRouteImport } from './routes/online-courses'
import { Route as MembershipFaqsRouteImport } from './routes/membership-faqs'
import { Route as MembershipRouteImport } from './routes/membership'
import { Route as LocalChaptersRouteImport } from './routes/local-chapters'
import { Route as EventsRouteImport } from './routes/events'
import { Route as EnterprisePartnersRouteImport } from './routes/enterprise-partners'
import { Route as ElearningGiftsRouteImport } from './routes/elearning-gifts'
import { Route as DiscussionsRouteImport } from './routes/discussions'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CommunityLatestRouteImport } from './routes/community-latest'
import { Route as CertificationsRouteImport } from './routes/certifications'
import { Route as CertificationProcessRouteImport } from './routes/certification-process'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as BlogsRouteImport } from './routes/blogs'
import { Route as AdvertisingRouteImport } from './routes/advertising'
import { Route as AccessibilityRouteImport } from './routes/accessibility'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardContactResponsesRouteImport } from './routes/dashboard/contact-responses'
import { Route as DashboardCertificationsRouteImport } from './routes/dashboard/certifications'

const WhatIsPmRoute = WhatIsPmRouteImport.update({
  id: '/what-is-pm',
  path: '/what-is-pm',
  getParentRoute: () => rootRouteImport,
} as any)
const WebinarsRoute = WebinarsRouteImport.update({
  id: '/webinars',
  path: '/webinars',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainingPartnersRoute = TrainingPartnersRouteImport.update({
  id: '/training-partners',
  path: '/training-partners',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesRoute = TemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreHelpRoute = StoreHelpRouteImport.update({
  id: '/store-help',
  path: '/store-help',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreRoute = StoreRouteImport.update({
  id: '/store',
  path: '/store',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapRoute = SitemapRouteImport.update({
  id: '/sitemap',
  path: '/sitemap',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportPdusRoute = ReportPdusRouteImport.update({
  id: '/report-pdus',
  path: '/report-pdus',
  getParentRoute: () => rootRouteImport,
} as any)
const PurchasingTermsRoute = PurchasingTermsRouteImport.update({
  id: '/purchasing-terms',
  path: '/purchasing-terms',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PressRoute = PressRouteImport.update({
  id: '/press',
  path: '/press',
  getParentRoute: () => rootRouteImport,
} as any)
const PmiBlogRoute = PmiBlogRouteImport.update({
  id: '/pmi-blog',
  path: '/pmi-blog',
  getParentRoute: () => rootRouteImport,
} as any)
const PmbokGuideRoute = PmbokGuideRouteImport.update({
  id: '/pmbok-guide',
  path: '/pmbok-guide',
  getParentRoute: () => rootRouteImport,
} as any)
const OnlineCoursesRoute = OnlineCoursesRouteImport.update({
  id: '/online-courses',
  path: '/online-courses',
  getParentRoute: () => rootRouteImport,
} as any)
const MembershipFaqsRoute = MembershipFaqsRouteImport.update({
  id: '/membership-faqs',
  path: '/membership-faqs',
  getParentRoute: () => rootRouteImport,
} as any)
const MembershipRoute = MembershipRouteImport.update({
  id: '/membership',
  path: '/membership',
  getParentRoute: () => rootRouteImport,
} as any)
const LocalChaptersRoute = LocalChaptersRouteImport.update({
  id: '/local-chapters',
  path: '/local-chapters',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const EnterprisePartnersRoute = EnterprisePartnersRouteImport.update({
  id: '/enterprise-partners',
  path: '/enterprise-partners',
  getParentRoute: () => rootRouteImport,
} as any)
const ElearningGiftsRoute = ElearningGiftsRouteImport.update({
  id: '/elearning-gifts',
  path: '/elearning-gifts',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscussionsRoute = DiscussionsRouteImport.update({
  id: '/discussions',
  path: '/discussions',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityLatestRoute = CommunityLatestRouteImport.update({
  id: '/community-latest',
  path: '/community-latest',
  getParentRoute: () => rootRouteImport,
} as any)
const CertificationsRoute = CertificationsRouteImport.update({
  id: '/certifications',
  path: '/certifications',
  getParentRoute: () => rootRouteImport,
} as any)
const CertificationProcessRoute = CertificationProcessRouteImport.update({
  id: '/certification-process',
  path: '/certification-process',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogsRoute = BlogsRouteImport.update({
  id: '/blogs',
  path: '/blogs',
  getParentRoute: () => rootRouteImport,
} as any)
const AdvertisingRoute = AdvertisingRouteImport.update({
  id: '/advertising',
  path: '/advertising',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessibilityRoute = AccessibilityRouteImport.update({
  id: '/accessibility',
  path: '/accessibility',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardContactResponsesRoute =
  DashboardContactResponsesRouteImport.update({
    id: '/dashboard/contact-responses',
    path: '/dashboard/contact-responses',
    getParentRoute: () => rootRouteImport,
  } as any)
const DashboardCertificationsRoute = DashboardCertificationsRouteImport.update({
  id: '/dashboard/certifications',
  path: '/dashboard/certifications',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/accessibility': typeof AccessibilityRoute
  '/advertising': typeof AdvertisingRoute
  '/blogs': typeof BlogsRoute
  '/careers': typeof CareersRoute
  '/certification-process': typeof CertificationProcessRoute
  '/certifications': typeof CertificationsRoute
  '/community-latest': typeof CommunityLatestRoute
  '/contact': typeof ContactRoute
  '/discussions': typeof DiscussionsRoute
  '/elearning-gifts': typeof ElearningGiftsRoute
  '/enterprise-partners': typeof EnterprisePartnersRoute
  '/events': typeof EventsRoute
  '/local-chapters': typeof LocalChaptersRoute
  '/membership': typeof MembershipRoute
  '/membership-faqs': typeof MembershipFaqsRoute
  '/online-courses': typeof OnlineCoursesRoute
  '/pmbok-guide': typeof PmbokGuideRoute
  '/pmi-blog': typeof PmiBlogRoute
  '/press': typeof PressRoute
  '/privacy': typeof PrivacyRoute
  '/purchasing-terms': typeof PurchasingTermsRoute
  '/report-pdus': typeof ReportPdusRoute
  '/sitemap': typeof SitemapRoute
  '/store': typeof StoreRoute
  '/store-help': typeof StoreHelpRoute
  '/templates': typeof TemplatesRoute
  '/terms': typeof TermsRoute
  '/training-partners': typeof TrainingPartnersRoute
  '/webinars': typeof WebinarsRoute
  '/what-is-pm': typeof WhatIsPmRoute
  '/dashboard/certifications': typeof DashboardCertificationsRoute
  '/dashboard/contact-responses': typeof DashboardContactResponsesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/accessibility': typeof AccessibilityRoute
  '/advertising': typeof AdvertisingRoute
  '/blogs': typeof BlogsRoute
  '/careers': typeof CareersRoute
  '/certification-process': typeof CertificationProcessRoute
  '/certifications': typeof CertificationsRoute
  '/community-latest': typeof CommunityLatestRoute
  '/contact': typeof ContactRoute
  '/discussions': typeof DiscussionsRoute
  '/elearning-gifts': typeof ElearningGiftsRoute
  '/enterprise-partners': typeof EnterprisePartnersRoute
  '/events': typeof EventsRoute
  '/local-chapters': typeof LocalChaptersRoute
  '/membership': typeof MembershipRoute
  '/membership-faqs': typeof MembershipFaqsRoute
  '/online-courses': typeof OnlineCoursesRoute
  '/pmbok-guide': typeof PmbokGuideRoute
  '/pmi-blog': typeof PmiBlogRoute
  '/press': typeof PressRoute
  '/privacy': typeof PrivacyRoute
  '/purchasing-terms': typeof PurchasingTermsRoute
  '/report-pdus': typeof ReportPdusRoute
  '/sitemap': typeof SitemapRoute
  '/store': typeof StoreRoute
  '/store-help': typeof StoreHelpRoute
  '/templates': typeof TemplatesRoute
  '/terms': typeof TermsRoute
  '/training-partners': typeof TrainingPartnersRoute
  '/webinars': typeof WebinarsRoute
  '/what-is-pm': typeof WhatIsPmRoute
  '/dashboard/certifications': typeof DashboardCertificationsRoute
  '/dashboard/contact-responses': typeof DashboardContactResponsesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/accessibility': typeof AccessibilityRoute
  '/advertising': typeof AdvertisingRoute
  '/blogs': typeof BlogsRoute
  '/careers': typeof CareersRoute
  '/certification-process': typeof CertificationProcessRoute
  '/certifications': typeof CertificationsRoute
  '/community-latest': typeof CommunityLatestRoute
  '/contact': typeof ContactRoute
  '/discussions': typeof DiscussionsRoute
  '/elearning-gifts': typeof ElearningGiftsRoute
  '/enterprise-partners': typeof EnterprisePartnersRoute
  '/events': typeof EventsRoute
  '/local-chapters': typeof LocalChaptersRoute
  '/membership': typeof MembershipRoute
  '/membership-faqs': typeof MembershipFaqsRoute
  '/online-courses': typeof OnlineCoursesRoute
  '/pmbok-guide': typeof PmbokGuideRoute
  '/pmi-blog': typeof PmiBlogRoute
  '/press': typeof PressRoute
  '/privacy': typeof PrivacyRoute
  '/purchasing-terms': typeof PurchasingTermsRoute
  '/report-pdus': typeof ReportPdusRoute
  '/sitemap': typeof SitemapRoute
  '/store': typeof StoreRoute
  '/store-help': typeof StoreHelpRoute
  '/templates': typeof TemplatesRoute
  '/terms': typeof TermsRoute
  '/training-partners': typeof TrainingPartnersRoute
  '/webinars': typeof WebinarsRoute
  '/what-is-pm': typeof WhatIsPmRoute
  '/dashboard/certifications': typeof DashboardCertificationsRoute
  '/dashboard/contact-responses': typeof DashboardContactResponsesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/accessibility'
    | '/advertising'
    | '/blogs'
    | '/careers'
    | '/certification-process'
    | '/certifications'
    | '/community-latest'
    | '/contact'
    | '/discussions'
    | '/elearning-gifts'
    | '/enterprise-partners'
    | '/events'
    | '/local-chapters'
    | '/membership'
    | '/membership-faqs'
    | '/online-courses'
    | '/pmbok-guide'
    | '/pmi-blog'
    | '/press'
    | '/privacy'
    | '/purchasing-terms'
    | '/report-pdus'
    | '/sitemap'
    | '/store'
    | '/store-help'
    | '/templates'
    | '/terms'
    | '/training-partners'
    | '/webinars'
    | '/what-is-pm'
    | '/dashboard/certifications'
    | '/dashboard/contact-responses'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/accessibility'
    | '/advertising'
    | '/blogs'
    | '/careers'
    | '/certification-process'
    | '/certifications'
    | '/community-latest'
    | '/contact'
    | '/discussions'
    | '/elearning-gifts'
    | '/enterprise-partners'
    | '/events'
    | '/local-chapters'
    | '/membership'
    | '/membership-faqs'
    | '/online-courses'
    | '/pmbok-guide'
    | '/pmi-blog'
    | '/press'
    | '/privacy'
    | '/purchasing-terms'
    | '/report-pdus'
    | '/sitemap'
    | '/store'
    | '/store-help'
    | '/templates'
    | '/terms'
    | '/training-partners'
    | '/webinars'
    | '/what-is-pm'
    | '/dashboard/certifications'
    | '/dashboard/contact-responses'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/accessibility'
    | '/advertising'
    | '/blogs'
    | '/careers'
    | '/certification-process'
    | '/certifications'
    | '/community-latest'
    | '/contact'
    | '/discussions'
    | '/elearning-gifts'
    | '/enterprise-partners'
    | '/events'
    | '/local-chapters'
    | '/membership'
    | '/membership-faqs'
    | '/online-courses'
    | '/pmbok-guide'
    | '/pmi-blog'
    | '/press'
    | '/privacy'
    | '/purchasing-terms'
    | '/report-pdus'
    | '/sitemap'
    | '/store'
    | '/store-help'
    | '/templates'
    | '/terms'
    | '/training-partners'
    | '/webinars'
    | '/what-is-pm'
    | '/dashboard/certifications'
    | '/dashboard/contact-responses'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AccessibilityRoute: typeof AccessibilityRoute
  AdvertisingRoute: typeof AdvertisingRoute
  BlogsRoute: typeof BlogsRoute
  CareersRoute: typeof CareersRoute
  CertificationProcessRoute: typeof CertificationProcessRoute
  CertificationsRoute: typeof CertificationsRoute
  CommunityLatestRoute: typeof CommunityLatestRoute
  ContactRoute: typeof ContactRoute
  DiscussionsRoute: typeof DiscussionsRoute
  ElearningGiftsRoute: typeof ElearningGiftsRoute
  EnterprisePartnersRoute: typeof EnterprisePartnersRoute
  EventsRoute: typeof EventsRoute
  LocalChaptersRoute: typeof LocalChaptersRoute
  MembershipRoute: typeof MembershipRoute
  MembershipFaqsRoute: typeof MembershipFaqsRoute
  OnlineCoursesRoute: typeof OnlineCoursesRoute
  PmbokGuideRoute: typeof PmbokGuideRoute
  PmiBlogRoute: typeof PmiBlogRoute
  PressRoute: typeof PressRoute
  PrivacyRoute: typeof PrivacyRoute
  PurchasingTermsRoute: typeof PurchasingTermsRoute
  ReportPdusRoute: typeof ReportPdusRoute
  SitemapRoute: typeof SitemapRoute
  StoreRoute: typeof StoreRoute
  StoreHelpRoute: typeof StoreHelpRoute
  TemplatesRoute: typeof TemplatesRoute
  TermsRoute: typeof TermsRoute
  TrainingPartnersRoute: typeof TrainingPartnersRoute
  WebinarsRoute: typeof WebinarsRoute
  WhatIsPmRoute: typeof WhatIsPmRoute
  DashboardCertificationsRoute: typeof DashboardCertificationsRoute
  DashboardContactResponsesRoute: typeof DashboardContactResponsesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/what-is-pm': {
      id: '/what-is-pm'
      path: '/what-is-pm'
      fullPath: '/what-is-pm'
      preLoaderRoute: typeof WhatIsPmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/webinars': {
      id: '/webinars'
      path: '/webinars'
      fullPath: '/webinars'
      preLoaderRoute: typeof WebinarsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/training-partners': {
      id: '/training-partners'
      path: '/training-partners'
      fullPath: '/training-partners'
      preLoaderRoute: typeof TrainingPartnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates': {
      id: '/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof TemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/store-help': {
      id: '/store-help'
      path: '/store-help'
      fullPath: '/store-help'
      preLoaderRoute: typeof StoreHelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/store': {
      id: '/store'
      path: '/store'
      fullPath: '/store'
      preLoaderRoute: typeof StoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap': {
      id: '/sitemap'
      path: '/sitemap'
      fullPath: '/sitemap'
      preLoaderRoute: typeof SitemapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report-pdus': {
      id: '/report-pdus'
      path: '/report-pdus'
      fullPath: '/report-pdus'
      preLoaderRoute: typeof ReportPdusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/purchasing-terms': {
      id: '/purchasing-terms'
      path: '/purchasing-terms'
      fullPath: '/purchasing-terms'
      preLoaderRoute: typeof PurchasingTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/press': {
      id: '/press'
      path: '/press'
      fullPath: '/press'
      preLoaderRoute: typeof PressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pmi-blog': {
      id: '/pmi-blog'
      path: '/pmi-blog'
      fullPath: '/pmi-blog'
      preLoaderRoute: typeof PmiBlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pmbok-guide': {
      id: '/pmbok-guide'
      path: '/pmbok-guide'
      fullPath: '/pmbok-guide'
      preLoaderRoute: typeof PmbokGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/online-courses': {
      id: '/online-courses'
      path: '/online-courses'
      fullPath: '/online-courses'
      preLoaderRoute: typeof OnlineCoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/membership-faqs': {
      id: '/membership-faqs'
      path: '/membership-faqs'
      fullPath: '/membership-faqs'
      preLoaderRoute: typeof MembershipFaqsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/membership': {
      id: '/membership'
      path: '/membership'
      fullPath: '/membership'
      preLoaderRoute: typeof MembershipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/local-chapters': {
      id: '/local-chapters'
      path: '/local-chapters'
      fullPath: '/local-chapters'
      preLoaderRoute: typeof LocalChaptersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/enterprise-partners': {
      id: '/enterprise-partners'
      path: '/enterprise-partners'
      fullPath: '/enterprise-partners'
      preLoaderRoute: typeof EnterprisePartnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/elearning-gifts': {
      id: '/elearning-gifts'
      path: '/elearning-gifts'
      fullPath: '/elearning-gifts'
      preLoaderRoute: typeof ElearningGiftsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discussions': {
      id: '/discussions'
      path: '/discussions'
      fullPath: '/discussions'
      preLoaderRoute: typeof DiscussionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community-latest': {
      id: '/community-latest'
      path: '/community-latest'
      fullPath: '/community-latest'
      preLoaderRoute: typeof CommunityLatestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/certifications': {
      id: '/certifications'
      path: '/certifications'
      fullPath: '/certifications'
      preLoaderRoute: typeof CertificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/certification-process': {
      id: '/certification-process'
      path: '/certification-process'
      fullPath: '/certification-process'
      preLoaderRoute: typeof CertificationProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blogs': {
      id: '/blogs'
      path: '/blogs'
      fullPath: '/blogs'
      preLoaderRoute: typeof BlogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/advertising': {
      id: '/advertising'
      path: '/advertising'
      fullPath: '/advertising'
      preLoaderRoute: typeof AdvertisingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accessibility': {
      id: '/accessibility'
      path: '/accessibility'
      fullPath: '/accessibility'
      preLoaderRoute: typeof AccessibilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/contact-responses': {
      id: '/dashboard/contact-responses'
      path: '/dashboard/contact-responses'
      fullPath: '/dashboard/contact-responses'
      preLoaderRoute: typeof DashboardContactResponsesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/certifications': {
      id: '/dashboard/certifications'
      path: '/dashboard/certifications'
      fullPath: '/dashboard/certifications'
      preLoaderRoute: typeof DashboardCertificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AccessibilityRoute: AccessibilityRoute,
  AdvertisingRoute: AdvertisingRoute,
  BlogsRoute: BlogsRoute,
  CareersRoute: CareersRoute,
  CertificationProcessRoute: CertificationProcessRoute,
  CertificationsRoute: CertificationsRoute,
  CommunityLatestRoute: CommunityLatestRoute,
  ContactRoute: ContactRoute,
  DiscussionsRoute: DiscussionsRoute,
  ElearningGiftsRoute: ElearningGiftsRoute,
  EnterprisePartnersRoute: EnterprisePartnersRoute,
  EventsRoute: EventsRoute,
  LocalChaptersRoute: LocalChaptersRoute,
  MembershipRoute: MembershipRoute,
  MembershipFaqsRoute: MembershipFaqsRoute,
  OnlineCoursesRoute: OnlineCoursesRoute,
  PmbokGuideRoute: PmbokGuideRoute,
  PmiBlogRoute: PmiBlogRoute,
  PressRoute: PressRoute,
  PrivacyRoute: PrivacyRoute,
  PurchasingTermsRoute: PurchasingTermsRoute,
  ReportPdusRoute: ReportPdusRoute,
  SitemapRoute: SitemapRoute,
  StoreRoute: StoreRoute,
  StoreHelpRoute: StoreHelpRoute,
  TemplatesRoute: TemplatesRoute,
  TermsRoute: TermsRoute,
  TrainingPartnersRoute: TrainingPartnersRoute,
  WebinarsRoute: WebinarsRoute,
  WhatIsPmRoute: WhatIsPmRoute,
  DashboardCertificationsRoute: DashboardCertificationsRoute,
  DashboardContactResponsesRoute: DashboardContactResponsesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
